spring.application.name=service
spring.threads.virtual.enabled=true
server.port=8081
#
spring.datasource.url=jdbc:postgresql://localhost:30000/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
#
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090
#
spring.flyway.enabled=false
