spring.application.name=client
server.port=8080
#
spring.security.oauth2.client.registration.myclient.provider=myprovider
spring.security.oauth2.client.registration.myclient.client-id=myclient
spring.security.oauth2.client.registration.myclient.client-secret=mysecret
spring.security.oauth2.client.registration.myclient.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.myclient.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.myclient.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.myclient.scope=openid,profile
#
spring.security.oauth2.client.provider.myprovider.issuer-uri=http://localhost:9090
